/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import konfiguracija.Konfiguracija;

/**
 *
 * @author HP
 */
public class PregledKonfiguracijeForma extends javax.swing.JDialog {

    private boolean ispravniPodaci = true;
    
    public PregledKonfiguracijeForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Konfiguracija");
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelURL = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelURL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelURL.setText("URL:");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUsername.setText("Username:");

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPassword.setText("Password:");

        jPasswordFieldPassword.setText("jPasswordField1");

        jLabelPort.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPort.setText("Port:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelURL)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelPassword)
                    .addComponent(jLabelPort))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jTextFieldUrl)
                    .addComponent(jPasswordFieldPassword)
                    .addComponent(jTextFieldPort))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelURL)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPort)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    public void ucitajPodatke() {
        String port = Konfiguracija.getInstance().ucitajPodatak("port");
        if (port == null) {
            jTextFieldPort.setText("Neispravan broj porta.");
            jTextFieldPort.setForeground(Color.RED);
        } else {
            jTextFieldPort.setText(port.trim());
        }
        String korisnik = Konfiguracija.getInstance().ucitajPodatak("username");
        String lozinka = Konfiguracija.getInstance().ucitajPodatak("password");
        String url = Konfiguracija.getInstance().ucitajPodatak("url");

        jTextFieldPort.setText(port != null ? port.trim() : "N/A");
        jTextFieldUrl.setText(url != null ? url.trim() : "N/A");
        jTextFieldUsername.setText(korisnik != null ? korisnik.trim() : "N/A");

        if (lozinka == null || lozinka.isEmpty()) {
            jPasswordFieldPassword.setText("");
        } else {
            jPasswordFieldPassword.setText(lozinka.trim());
        }
        
        jTextFieldPort.setEditable(false);
        jTextFieldUrl.setEditable(false);
        jTextFieldUsername.setEditable(false);
        jPasswordFieldPassword.setEditable(false);
        
//        System.out.println("Korisnik iz konfiguracije: " + korisnik);



    }
    boolean proveriPodatke() {
        String portText = jTextFieldPort.getText().trim();
        String url = jTextFieldUrl.getText().trim();
        String korisnik = jTextFieldUsername.getText().trim();
        int port;

        if (portText.trim().isEmpty() || portText.trim().equals("N/A") || korisnik.trim().isEmpty() || korisnik.trim().equals("N/A") || url.trim().isEmpty() || url.trim().equals("N/A")) {
            ispravniPodaci = false;
            return ispravniPodaci;
        }
        try {
            port = Integer.parseInt(portText);
        } catch (NumberFormatException numberFormatException) {
            ispravniPodaci = false;
            return ispravniPodaci;
        }
        if (port < 0 || port > 65536) {
            ispravniPodaci = false;
            return ispravniPodaci;
        }

        return ispravniPodaci;
    }

    public boolean isIspravniPodaci() {
        return ispravniPodaci;
    }

    public void setIspravniPodaci(boolean ispravniPodaci) {
        this.ispravniPodaci = ispravniPodaci;
    }

    public JLabel getjLabelPassword() {
        return jLabelPassword;
    }

    public void setjLabelPassword(JLabel jLabelPassword) {
        this.jLabelPassword = jLabelPassword;
    }

    public JLabel getjLabelPort() {
        return jLabelPort;
    }

    public void setjLabelPort(JLabel jLabelPort) {
        this.jLabelPort = jLabelPort;
    }

    public JLabel getjLabelURL() {
        return jLabelURL;
    }

    public void setjLabelURL(JLabel jLabelURL) {
        this.jLabelURL = jLabelURL;
    }

    public JLabel getjLabelUsername() {
        return jLabelUsername;
    }

    public void setjLabelUsername(JLabel jLabelUsername) {
        this.jLabelUsername = jLabelUsername;
    }

    public JPasswordField getjPasswordFieldPassword() {
        return jPasswordFieldPassword;
    }

    public void setjPasswordFieldPassword(JPasswordField jPasswordFieldPassword) {
        this.jPasswordFieldPassword = jPasswordFieldPassword;
    }

    public JTextField getjTextFieldPort() {
        return jTextFieldPort;
    }

    public void setjTextFieldPort(JTextField jTextFieldPort) {
        this.jTextFieldPort = jTextFieldPort;
    }

    public JTextField getjTextFieldUrl() {
        return jTextFieldUrl;
    }

    public void setjTextFieldUrl(JTextField jTextFieldUrl) {
        this.jTextFieldUrl = jTextFieldUrl;
    }

    public JTextField getjTextFieldUsername() {
        return jTextFieldUsername;
    }

    public void setjTextFieldUsername(JTextField jTextFieldUsername) {
        this.jTextFieldUsername = jTextFieldUsername;
    }
    

}
