/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author HP
 */
public enum Operacije implements Serializable {
    PRIJAVI_PRODAVAC,
    DODAJ_PRIJAVLJENOG,
    ODJAVI_SE,
    VRATI_LISTU_SVI_PRODAVCI,
    VRATI_LISTU_SVI_MESTO,
    KREIRAJ_KUPAC,
    PROMENI_KUPAC,
    OBRISI_KUPAC,
    VRATI_LISTU_SVI_KUPCI,
    VRATI_LISTU_KUPAC_KUPAC,
    VRATI_LISTU_KUPAC_MESTO,
    PRETRAZI_KUPAC,
    KREIRAJ_PRODAVAC,
    PROMENI_PRODAVAC,
    OBRISI_PRODAVAC,
    VRATI_LISTU_SVI_TERMIN_DEZURSTVA,
    VRATI_LISTU_PRODAVAC_PRODAVAC,
    VRATI_LISTU_PRODAVAC_TERMIN,
    PRETRAZI_PRODAVAC,
    UBACI_TERMIN,
    PROMENI_TERMIN,
    OBRISI_TERMIN,
    VRATI_LISTU_TERMIN_TERMIN,
    PRETRAZI_TERMIN,
    KREIRAJ_IZNAJMLJIVANJE,
    PROMENI_IZNAJMLJIVANJE,
    VRATI_LISTU_SVA_IZNAJMLJIVANJA,
    VRATI_LISTU_IZNAJMLJIVANJE_IZNAJMLJIVANJE,
    VRATI_LISTU_IZNAJMLJIVANJE_PRODAVAC,
    VRATI_LISTU_IZNAJMLJIVANJE_KUPAC,
    VRATI_LISTU_IZNAJMLJIVANJE_BICIKLA,
    PRETRAZI_IZNAJMLJIVANJE,
    VRATI_LISTU_SVI_BICIKLA,
    KREIRAJ_BICIKLA,
    PROMENI_BICIKLA,
    OBRISI_BICIKLA,
    VRATI_LISTU_BICIKLA_BICIKLA,
    PRETRAZI_BICIKLA,
    KREIRAJ_MESTO,
    PRETRAZI_MESTO,
    PROMENI_MESTO,
    OBRISI_MESTO,
    VRATI_LISTU_MESTO_MESTO,
}
