/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


/**
 *
 * @author HP
 */
public class LoginForma extends javax.swing.JFrame {

    
    public LoginForma() {
        initComponents();
        this.setTitle("Prijava na sistem");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonPrijava = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();
        jTextFieldKorisnickoIme = new javax.swing.JTextField();
        jPasswordFieldSifra = new javax.swing.JPasswordField();
        jButtonPrikaziSifru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PRIJAVITE SE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Korisničko ime:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Šifra:");

        jButtonPrijava.setBackground(new java.awt.Color(0, 0, 255));
        jButtonPrijava.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonPrijava.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrijava.setText("Prijavi se");
        jButtonPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrijavaActionPerformed(evt);
            }
        });

        jButtonOtkazi.setBackground(new java.awt.Color(255, 0, 0));
        jButtonOtkazi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonOtkazi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOtkazi.setText("Otkaži");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jPasswordFieldSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSifraActionPerformed(evt);
            }
        });

        jButtonPrikaziSifru.setText("👁");
        jButtonPrikaziSifru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSifruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldSifra, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jTextFieldKorisnickoIme))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jButtonPrikaziSifru)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrikaziSifru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrijavaActionPerformed
        
    }//GEN-LAST:event_jButtonPrijavaActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
//        String[] options = {"Da", "Ne"};
//        int odgovor = JOptionPane.showOptionDialog(
//            this, 
//            "Da li ste sigurni da želite da napustite prijavu?", 
//            "Potvrda", 
//            JOptionPane.YES_NO_OPTION, 
//            JOptionPane.QUESTION_MESSAGE, 
//            null, 
//            options, 
//            options[0]
//        );
//        if (odgovor == JOptionPane.YES_OPTION) {
//            this.dispose(); 
//        }
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jButtonPrikaziSifruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSifruActionPerformed
//        if (jPasswordFieldSifra.getEchoChar() == (char)0) { // Proverava da li su šifre maskirane
//            jPasswordFieldSifra.setEchoChar('*'); // Prikazuje šifru
//        } else {
//            jPasswordFieldSifra.setEchoChar((char)0); // Maskira šifru ponovo (korišćenje tačke)
//        }
        
    }//GEN-LAST:event_jButtonPrikaziSifruActionPerformed

    private void jPasswordFieldSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSifraActionPerformed

    public JButton getjButtonPrijava() {
        return jButtonPrijava;
    }

    public void setjButtonPrijava(JButton jButtonPrijava) {
        this.jButtonPrijava = jButtonPrijava;
    }

    public JPasswordField getjPasswordFieldSifra() {
        return jPasswordFieldSifra;
    }

    public void setjPasswordFieldSifra(JPasswordField jPasswordFieldSifra) {
        this.jPasswordFieldSifra = jPasswordFieldSifra;
    }

    public JTextField getjTextFieldKorisnickoIme() {
        return jTextFieldKorisnickoIme;
    }

    public void setjTextFieldKorisnickoIme(JTextField jTextFieldKorisnickoIme) {
        this.jTextFieldKorisnickoIme = jTextFieldKorisnickoIme;
    }

    public JButton getjButtonPrikaziSifru() {
        return jButtonPrikaziSifru;
    }

    public void setjButtonPrikaziSifru(JButton jButtonPrikaziSifru) {
        this.jButtonPrikaziSifru = jButtonPrikaziSifru;
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonPrijava;
    private javax.swing.JButton jButtonPrikaziSifru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldSifra;
    private javax.swing.JTextField jTextFieldKorisnickoIme;
    // End of variables declaration//GEN-END:variables

   

    public void loginAddActionListener(ActionListener actionListener) {
        jButtonPrijava.addActionListener(actionListener);
    }

    public void prikaziSifruAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziSifru.addActionListener(actionListener);
    }

    public void otkaziAddActionListeners(ActionListener actionListener) {
        jButtonOtkazi.addActionListener(actionListener);
    }
}
